workflows:
  humai_flutter:
    name: HumAI Digital Twin - Flutter
    max_build_duration: 60

    environment:
      flutter: stable

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build APK (release)
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk